Add new aws_cost_collector module
Signiant/aws-team-cost-reporter pull request #1
Opened 2018-01-23 21:14 UTC by haggaret

Add new aws_cost_collector module for getting data from the AWS Cost Explorer, instead of from cloudcheckr

I've sort of written each file (s3.py, etc) as a standalone unit that can be called, but they are also imported into aws_cost_collector and used from there. Can easily remove the main method if you don't like that/think it has any benefit.

2018-01-23 21:31 UTC, dnorth98 requested changes

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/aws_cost_collector.py
> +        group_by_tag = 'signiant:email'
Remove this.  The tags are in the config file.  There should be nothing Signiant specific in the code

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/aws_cost_collector.py
> +        group_by_tag = "aws:cloudformation:stack-name"
Same as previous comment.  All tags should be in the config file

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/aws_cost_collector.py
> +    LOG_FILENAME = 'aws_cost_collector.log'
Should only log to STDOUT as this is designed to be run in a docker container

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/cloudcheckr_format.py
> +    #     "signant:email user1@domain" : [
Signiant specific tag

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/cloudcheckr_format.py
> +    #     "signant:email user2@domain" : [
Signiant specific tag

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/cloudcheckr_format.py
> +    #          "Name": "signiant:email user@domain.com",
Signiant specific tag

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/s3.py
> +    parser.add_argument("--aws-access-key-id", help="AWS Access Key ID", dest='aws_access_key', required=False)
Keys should be read from the environment, not passed in on the cli

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/s3.py
> +    parser.add_argument("--profile", help="The name of an aws cli profile to use.", dest='profile', default=None, required=False)
Cli profile?  Are we just calling the CLI?

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/aws_cost_collector/s3.py
> +    SESSION = boto3.session.Session(profile_name=args.profile, region_name=args.region)
Profile should be set in the environment

2018-01-23 21:31 UTC, dnorth98 commented on team-cost-reporter/plugins/s3/__init__.py
> +                aws_ce = config_plugin['aws_ce']
else?  fail I guess....

2018-01-24 15:47 UTC, haggaret commented
Ok, big changes made after @dnorth98's review. Have a look again Dave if you have a minute.

2018-01-24 15:48 UTC, haggaret commented on team-cost-reporter/aws_cost_collector.py
> +    SESSION = boto3.session.Session()
Actually, I'm not crazy about this - I think I'll move this outside this function - doesn't make sense to be inside it.

2018-01-24 15:53 UTC, dnorth98 approved these changes
yeah, I like this much more.  Much simpler.

2018-01-24 16:41 UTC, merged